# Generated by Django 4.2.11 on 2024-06-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
        migrations.AlterModelTable(
            name='url',
            table='URL',
        ),
    ]
